POST http://localhost:3001/status
content-type: application/json

{
    "token": "BQBpH3Qx41MT0yFJY63rp_qGhKdA0T8gJY9SjZ7bzLWgzf5qBXfWKmsBazZ826QprnczDZRqd2tcJ7bPnvFBZ-xtO9TK_d2Dmq5tcA9jN0dp3BJNKaxH63a4heHbD3Pgo68TVvIy4_i_Q4ZMrEOfUNbimBUmfBReuIuigWX4iI_xKLWhMMCA1hAX51E"
}

###

POST http://localhost:3001/device
content-type: application/json

{
    "token": "BQDCYZ3BGRwWNQVPit46-Rg4WsUTX0zkPHdI3DUeyG_WfTBoyi1ZX7LJvKcD-kwzBoLmGVJgJk-xTvMzvdsgBXhosIgjusdTLnue6_gV9WyNfQtrAjoWWv8vMC-gJFZI3CUv-T33g0uEy8psB2w2lXXHfRUTjdZa9A1dOH4L8UsZXu-xI-E_JyuJJ8CF"
}

###

GET http://localhost:3001/lyrics?artist='IU'&track='BBIBBI'

###

PUT http://localhost:3001/play
content-type: application/json

{
    "trackUri": "spotify:track:4as4XEOR03oGm1STUKl6pa",
    "token": "BQDCYZ3BGRwWNQVPit46-Rg4WsUTX0zkPHdI3DUeyG_WfTBoyi1ZX7LJvKcD-kwzBoLmGVJgJk-xTvMzvdsgBXhosIgjusdTLnue6_gV9WyNfQtrAjoWWv8vMC-gJFZI3CUv-T33g0uEy8psB2w2lXXHfRUTjdZa9A1dOH4L8UsZXu-xI-E_JyuJJ8CF"
}

###

PUT http://localhost:3001/pause
content-type: application/json

{
    "token": "BQDCYZ3BGRwWNQVPit46-Rg4WsUTX0zkPHdI3DUeyG_WfTBoyi1ZX7LJvKcD-kwzBoLmGVJgJk-xTvMzvdsgBXhosIgjusdTLnue6_gV9WyNfQtrAjoWWv8vMC-gJFZI3CUv-T33g0uEy8psB2w2lXXHfRUTjdZa9A1dOH4L8UsZXu-xI-E_JyuJJ8CF"
}
